version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: ["streamlit", "run", "./src/main.py", "--server.address=0.0.0.0"]
