version: "3.9"
services:
  vector_db:
    image: chromadb/chroma
    container_name: vector_db
    volumes:
      - ./vectordb:/chroma
    ports:
      - "8001:8000"

  storage_service:
    build: .
    container_name: storage_service
    depends_on:
      - vector_db
    ports:
      - "8002:8000"
    command: ["uvicorn", "services.storage_service:app", "--host", "0.0.0.0", "--port", "8000"]

  qa_service:
    build: .
    container_name: qa_service
    depends_on:
      - storage_service
    ports:
      - "8003:8000"
    command: ["uvicorn", "services.qa_service:app", "--host", "0.0.0.0", "--port", "8000"]
